### ISSUE TITLE
java.lang.IllegalStateException: Need to call #setCharacterLists first

### ISSUE THREAD

**Issue by akshaychopra96** [robinhood/ticker#95]
I have  initialised CharacterList in onCreate() method . It is still giving the following error:

Caused by: java.lang.IllegalStateException: Need to call #setCharacterLists first.
        at com.robinhood.ticker.TickerColumnManager.setText(TickerColumnManager.java:71)
        at com.robinhood.ticker.TickerView.setText(TickerView.java:299)
        at com.robinhood.ticker.TickerView.init(TickerView.java:180)

**Comment by jinatonic** [comment]
Are you using the `android:text` attribute in XML? if so, there is a known issue where it'll crash on initialization.
